## Lab six Omar Elalem(8937288)

### 1. Using SciKit-Learn, train a binary logistic regression model on the Iris dataset. Use all four features and define only 2 labels: virginica and non-virginica. See the logistic regression notebook presented in class for a demonstration on how to set up these labels (3 points).

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report
sns.set_style("whitegrid")

#### loading dataset

In [2]:
irisdf = load_iris()

#### where X is a matrix of independent variables and yis the dependent variable

In [3]:
X = irisdf.data 
y = irisdf.target 

####  Encoding label into two categories: virginica and non-virginica

In [4]:
label_encoder = LabelEncoder() 
y = label_encoder.fit_transform(irisdf.target_names[y])

#### split the data into training and test data

In [5]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

#### Building Logistic regression model

In [6]:
## Building Logistic regression model
logReg = LogisticRegression()

#### Fitting the model on training data

In [7]:

logReg.fit(X_train, y_train)

c:\Users\20102\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### making prediction

In [9]:
y_pred = logReg.predict(X_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2], dtype=int64)

In [10]:
Accuracy = accuracy_score(y_test, y_pred)
print("Accuracy is:", Accuracy)

Accuracy is: 0.9666666666666667


#### creating confusion matrix

In [11]:
Confusion_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(Confusion_matrix)

Confusion Matrix:
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


#### Creating the classification report

In [12]:
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



### Evaluate the model:
### Failure modes: in which data instances is the model wrong? (1 point)
### Are there any shared properties for these cases? (1 point)
### How is the model doing across a set of evaluation metrics: accuracy and confusion metric. (1 point)

#### Identfying the indices where model predictied falsely

In [13]:
misclassifiedIndices = np.where(y_test != y_pred)[0]
misclassifiedIndices

array([22], dtype=int64)

In [14]:
for i in misclassifiedIndices:
    print("the model predicted ",y_pred[i]," where it is supposed to predict ",y_test[i])

the model predicted  2  where it is supposed to predict  1


#### I was unable to determine the shared features of the falsly predicted items because it was only one item 
#### NA false positive or false negative